server.port=8080
spring.application.name=api-in-a-box

# OAuth2 Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://your-oauth2-provider
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://your-oauth2-provider/.well-known/jwks.json

# JWT Configuration
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:public-key.pem
spring.security.oauth2.resourceserver.jwt.audiences=api-in-a-box

# Authorization Configuration
app.authorization-enabled=false